# Generated by Django 3.0 on 2019-12-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('idcalificaciones', models.AutoField(db_column='idCalificaciones', primary_key=True, serialize=False)),
                ('calificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('idelenco', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'elenco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('idpeliculas', models.AutoField(db_column='idPeliculas', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=45)),
                ('fecha', models.DateField(blank=True, db_column='FechaEstreno', null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'db_table': 'peliculas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('idpersonajes', models.IntegerField(primary_key=True, serialize=False)),
                ('personaje', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersonas', primary_key=True, serialize=False)),
                ('persona', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipospersonas',
            fields=[
                ('idtipospersonas', models.AutoField(db_column='idTiposPersonas', primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tipo de Persona',
                'verbose_name_plural': 'Tipos de Personas',
                'db_table': 'tipospersonas',
                'managed': False,
            },
        ),
    ]
