# Generated by Django 2.2.7 on 2019-11-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('idcalificaciones', models.AutoField(db_column='idCalificaciones', primary_key=True, serialize=False)),
                ('calificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.TimeField(auto_now_add=True)),
                ('actualizado', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('idnotas', models.AutoField(db_column='idNotas', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('pdf', models.TextField(blank=True, null=True)),
                ('creado', models.TimeField(auto_now_add=True)),
                ('actualizado', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersonas', primary_key=True, serialize=False)),
                ('persona', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('idregiones', models.AutoField(db_column='idRegiones', primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.TimeField(auto_now_add=True)),
                ('actualizado', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'db_table': 'regiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('idsecciones', models.AutoField(db_column='idSecciones', primary_key=True, serialize=False)),
                ('seccion', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.TimeField(auto_now_add=True)),
                ('actualizado', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
                'db_table': 'secciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipospersonas',
            fields=[
                ('idtipospersonas', models.AutoField(db_column='idTiposPersonas', primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Persona',
                'verbose_name_plural': 'Tipos de Personas',
                'db_table': 'tipospersonas',
                'managed': False,
            },
        ),
    ]
