# Generated by Django 2.2.7 on 2019-11-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('idpeliculas', models.AutoField(db_column='idNotas', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.TimeField(auto_now_add=True)),
                ('actualizado', models.TimeField(auto_now=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'db_table': 'peliculas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
        migrations.DeleteModel(
            name='Regiones',
        ),
        migrations.DeleteModel(
            name='Secciones',
        ),
    ]
