# Generated by Django 3.0 on 2019-12-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('idcalificaciones', models.AutoField(db_column='idCalificaciones', primary_key=True, serialize=False)),
                ('calificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('idpersonajes', models.IntegerField(primary_key=True, serialize=False)),
                ('personaje', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personajes',
            },
        ),
        migrations.CreateModel(
            name='Tipospersonas',
            fields=[
                ('idtipospersonas', models.AutoField(db_column='idTiposPersonas', primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('prioridad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tipo de Persona',
                'verbose_name_plural': 'Tipos de Personas',
                'db_table': 'tipospersonas',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersonas', primary_key=True, serialize=False)),
                ('persona', models.CharField(blank=True, max_length=45, null=True)),
                ('estatus', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipospersonas_idTiposPersonas', models.ForeignKey(db_column='TiposPersonas_idTiposPersonas', on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Tipospersonas')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Personas',
                'unique_together': {('idpersona', 'tipospersonas_idTiposPersonas')},
            },
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('idelenco', models.IntegerField(primary_key=True, serialize=False)),
                ('personajes_idpersonajes', models.ForeignKey(db_column='personajes_idpersonajes', on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Personajes')),
                ('personas_idpersonas', models.ForeignKey(db_column='Personas_idPersonas', on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Personas')),
            ],
            options={
                'db_table': 'elenco',
                'unique_together': {('personas_idpersonas', 'personajes_idpersonajes')},
            },
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('idpeliculas', models.AutoField(db_column='idPeliculas', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=45)),
                ('fecha', models.DateField(blank=True, db_column='FechaEstreno', null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('Categoria_idCategoria', models.ForeignKey(db_column='Categoria_idCategoria', on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Categorias', verbose_name='Categoría')),
                ('Personas_idPersonas', models.ForeignKey(db_column='personas_idpersonas', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portfolio.Personas', verbose_name='Director')),
                ('TiposPersonas_idTiposPersonas', models.ForeignKey(db_column='TiposPersonas_idTiposPersonas', on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Personas', verbose_name='Actor')),
                ('calificaciones_idcalificaciones', models.ForeignKey(db_column='Calificaciones_idCalificaciones', on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Calificaciones', verbose_name='Calificaciones')),
                ('cast', models.ManyToManyField(to='portfolio.Elenco')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'db_table': 'peliculas',
                'unique_together': {('idpeliculas', 'Categoria_idCategoria', 'calificaciones_idcalificaciones', 'Personas_idPersonas', 'TiposPersonas_idTiposPersonas')},
            },
        ),
    ]
