# Generated by Django 3.0 on 2019-12-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='tipospersonas',
            name='prioridad',
        ),
    ]
