# Generated by Django 3.0 on 2019-12-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20191204_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='estatus',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='estatus',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='personas',
            name='estatus',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tipospersonas',
            name='estatus',
            field=models.BooleanField(),
        ),
    ]
