# Generated by Django 3.0 on 2019-12-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20191204_1517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peliculas',
            unique_together={('idpeliculas', 'Categoria_idCategoria', 'calificaciones_idcalificaciones')},
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='Personas_idPersonas',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='TiposPersonas_idTiposPersonas',
        ),
    ]
