# Generated by Django 3.0 on 2019-12-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20191204_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elenco',
            name='idelenco',
            field=models.AutoField(db_column='idelenco', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='idpersonajes',
            field=models.AutoField(db_column='idpersonajes', primary_key=True, serialize=False),
        ),
    ]
