# Generated by Django 3.0 on 2019-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20191204_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='elenco',
            name='img',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='img',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='img',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
