# Generated by Django 3.0 on 2019-12-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20191205_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='Personas_idPersonas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Personas', verbose_name='Director'),
        ),
        migrations.AlterUniqueTogether(
            name='peliculas',
            unique_together={('idpeliculas', 'Categoria_idCategoria', 'calificaciones_idcalificaciones', 'Personas_idPersonas')},
        ),
    ]
