# Generated by Django 3.0 on 2019-12-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20191208_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='prioridad',
            new_name='duracion',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='banner',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
