# Generated by Django 3.0 on 2019-12-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20191205_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='Personas_idPersonas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Personas', verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='banner',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='logo',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='peliculas',
            unique_together={('idpeliculas', 'Categoria_idCategoria', 'calificaciones_idcalificaciones', 'Personas_idPersonas')},
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='prioridad',
        ),
    ]
