# Generated by Django 3.0 on 2019-12-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20191208_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='logo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
